### ISSUE TITLE
Solve 'Grasshopper - Debug'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#1]
https://www.codewars.com/kata/grasshopper-debug/train/javascript

**Comment by Deobp** [comment]
function weatherInfo (temp) {

  let celsius = (temp -32) * (5/9);
  let c = celsius;                           
  if (c < 0) {
    return (c + " is freezing temperature");
 } else {
return (c + " is above freezing temperature");
}
}

**Comment by odv** [comment]
@LaievskyiSasha  While your solution is correct, you don't need to rewrite the code completely. You just need to find the mistakes in the code and fix them.

**Comment by Deobp** [comment]
function weatherInfo (temp) {
  let c = temp;
  if (c < 0)
    return (c + " is freezing temperature");
  else
    return (c + " is above freezing temperature");
}

function convertToCelsius (temperature) {
  let celsius = (temperature - 32) * (5/9);
  return celsius;
}

dont know how to use second function into frist

**Comment by Deobp** [comment]
function weatherInfo (temp) {
  if (convertToCelsius(temp) < 0) {
    return (convertToCelsius(temp) + " is freezing temperature");
  } else {
    return (convertToCelsius(temp) + " is above freezing temperature");
  }
}

function convertToCelsius (temperature) {
return (temperature - 32) * (5/9);
}

@odv
