### ISSUE TITLE
Solve 'Grasshopper - Shopping list'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#12]
https://www.codewars.com/kata/grasshopper-shopping-list/train/javascript

**Comment by Deobp** [comment]
let sandwiches = 4;
let salads = 6;
let wraps = 5;
let frenchFries = 10;
let totalPrice = sandwiches * 8.00 + salads * 7.00 + wraps * 6.50 + frenchFries * 1.20;
