### ISSUE TITLE
Solve 'Initialize my name'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#123]
https://www.codewars.com/kata/initialize-my-name/train/javascript

**Comment by Deobp** [comment]
function initializeNames(name){
let shortName = [];
 if(name.length >2){
   for(let i =2; i >name.split(' ').length -1; i++){
     shortName.concat(name.split(' ')[i][0]);
 
 return `${name.split(' ')[0]} ${shortName.join('.').toUpperCase()} + ${name.split(' ')[-1]}`;
 }
 return name;
}

**Comment by Deobp** [comment]
```
function initializeNames(name){
let splitName = name.split(' ');
let output;
if (splitName.length > 2) {
  output = `${splitName[0]} `;  
  for (let i = 1; i < splitName.length -1; i++) {
    output += splitName[i][0] +'. ';   
  }
   return `${output}${splitName[splitName.length -1]}`;
}
  return name;

}



```
