### ISSUE TITLE
Will there be enough space?

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#14]
https://www.codewars.com/kata/will-there-be-enough-space/train/javascript

**Comment by LaievskyiSasha** [comment]
function enough(cap, on, wait) {
  if (cap<on) {
  return 0;
  } else {
  return on - wait;
  }
}

**Comment by Deobp** [comment]
function enough(cap, on, wait) {
  if (cap<on) {
  return 0;
  } else {
  return on - wait;
  }
}

**Comment by Deobp** [comment]
function enough(cap, on, wait) {
  if (cap - on<wait) {
  return wait+on-cap;
  } else  {
  return 0;
  }
}
