### ISSUE TITLE
Solve 'Find the Remainder?'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#17]
https://www.codewars.com/kata/find-the-remainder/train/javascript

**Comment by LaievskyiSasha** [comment]
function remainder(a, b){
 if (a<b) {
 return a/b;
 } else if (a=0 | b=0) {
 return NaN;
  } else {
  return b/a;
  }
}

**Comment by Deobp** [comment]
function remainder(a, b){
if (a ==0 || b == 0) {
 return NaN;
 } else if (a <  b) {
 return b%a;
 } else {
 return a%b;
 }
}
