### ISSUE TITLE
Solve 'Twice as old'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#170]
https://www.codewars.com/kata/twice-as-old/train/javascript

**Comment by Deobp** [comment]
```
function twiceAsOld(dadYearsOld, sonYearsOld) {
let twice = dadYearsOld - sonYearsOld * 2;
return twice < 0 ? twice * (-1) : twice;
}
```

**Comment by Zahid01711** [comment]
function twiceAsOld(dadYearsOld, sonYearsOld) {
  return Math.abs(dadYearsOld - 2 * sonYearsOld);
}

**Comment by Zahid01711** [comment]
const twiceAsOld = (d, s) => Math.abs(d - 2 * s);
