### ISSUE TITLE
Character Frequency

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#196]
https://www.codewars.com/kata/character-frequency-2/train/javascript

How to check how often is an element of an array/string occurse?

**Comment by odv** [comment]
@LaievskyiSasha  You first need to parse each character of your string. You can create a "database" which is an object where you store each character(hint: charAt(i);) and count the number of times it has been seen.

After that, you just return the object.

**Comment by Deobp** [comment]
```
function charFreq(message) {
    let frequency = {};

    for (let i = 0; i < message.length; i++) {
        let char = message[i];
        if (frequency[char]) {
            frequency[char] += 1;
        } else {
            frequency[char] = 1;
        }
    }
    return frequency;
}
```
