### ISSUE TITLE
Solve 'Return to Sanity'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#2]
https://www.codewars.com/kata/return-to-sanity/train/javascript

**Comment by Deobp** [comment]
// 0 idea

function mystery() {
  let results ={sanity: 'Hello'};
  return results;
}

**Comment by odv** [comment]
@LaievskyiSasha The function wasn't working because the value that should have been returned, was on the next line. JavaScript has a thing called 'automatic semicolon insertion' so it tries to automatically put a semicolon when the line terminates so in this case, it put a semicolon after return.

Why do you have that comment at the top?

**Comment by Deobp** [comment]
it works

**Comment by Deobp** [comment]
@odv 
function mystery() {
  return {sanity: 'Hello'};
}
