### ISSUE TITLE
Solve 'Drink about' 

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#20]
https://www.codewars.com/kata/drink-about

**Comment by LaievskyiSasha** [comment]
function peopleWithAgeDrink(old) {
if (old<14) {
return "drink toddy";
} else if (14<old<17) {
return "drink coke";
} else if (22>old>17) {
  return "drink beer" ;
  } else if (old > 20) {
 return "drink whisky";
  }
}

**Comment by Deobp** [comment]
function peopleWithAgeDrink(old) {
 if (old <= 13) {
  return "drink toddy";

} else if (17>=old) {
   return "drink coke";

} else if (20>=old) {
   return "drink beer";
  
  } else if  (old>=21) {
   return "drink whisky";
  }
}
