### ISSUE TITLE
FIXME: Replace all dots

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#218]
https://www.codewars.com/kata/fixme-replace-all-dots/train/javascript

```
let replaceDots = function(str) {
  return str.replace('.', '-');
}
```

It's string, and only 1 time method *.replace()* will replace string. How to replace multiple time?

**Comment by IvanBliudnik** [comment]
const replaceDots = (str) => str.replace(/\./g, '-')
console.log(replaceDots('hello...world'))
