### ISSUE TITLE
Abbreviate a Two Word Name (array)

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#22]
https://www.codewars.com/kata/abbreviate-a-two-word-name/train/javascript

**Comment by LaievskyiSasha** [comment]
function abbrevName(name){
let firstName = name.length[1];
let secondName = name.length[2];
return firstName[0] + secondName [0];
}

**Comment by LaievskyiSasha** [comment]
name is a 'string', need convert to array, execute [0] and [1] and then execute first latters

**Comment by LaievskyiSasha** [comment]
function abbrevName(name){
let twoName =name.split();
let firstName = twoName.length[0];
let secondName = twoName.length[1];
return firstName[0] + secondName[1];
}
