### ISSUE TITLE
Sum of Multiples

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#227]
https://www.codewars.com/kata/sum-of-multiples/train/javascript

```
function sumMul(n,m){
let sum = 0;
  if (m > n) {
    for (let i = n; i <= m; i+=n) {
      if(i%n == 0){
      sum += i;
      }
    }
return sum;
  } else {
return 'INVALID';
  }
}
```

**Comment by odv** [comment]
@LaievskyiSasha You have a logic mistake in your for loop. Also, why don't you start with what you need to output in case of failure and then move to what you need to return in case function is called with valid parameters?

You are not clear and organized in your thought process!

**Comment by Deobp** [comment]
```
function sumMul(n,m){
let sum = 0;
  if (m > n) {
    for (let i = n; i < m; i+=n) {
      sum += i;
    }
return sum;
  } else {
return 'INVALID';
  }
}



```
