### ISSUE TITLE
Solve 'Training JS #8: Conditional statement--switch'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#24]
https://www.codewars.com/kata/training-js-number-8-conditional-statement-switch/train/javascript

**Comment by Deobp** [comment]
function howManydays(month){
  let days;
  switch (month){
   case 2:
  days=28;
  break;
  case 4:
  case 6:
  case 9:
  case 11:
  days=30;
  break;
  case 2:
  days=28;
  break;
  default:
  days=31;
  }
  return days;
}

**Comment by Deobp** [comment]
function howManydays(month){
switch (month){
case 2:
return 28;
case 4:
case 6:
case 9:
case 11:
return 30;
case 2:
return 28;
default:
return 31;
}
}
