### ISSUE TITLE
Solve 'Grasshopper - Summation'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#25]
https://www.codewars.com/kata/grasshopper-summation/train/javascript

**Comment by Deobp** [comment]
var summation = function (num) {
let a=0;
for (i=0; i<num; i++)
a+=1;
return a;
}

**Comment by Deobp** [comment]
let summation = function (num) {
let a=0;
for (i=1; i <= num; i++) {
a+=i;
}
return a;
}
