### ISSUE TITLE
Solve 'Get Planet Name By ID'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#28]
https://www.codewars.com/kata/get-planet-name-by-id/train/javascript

**Comment by Deobp** [comment]
function getPlanetName(id){
  switch(id){
    case 1:
      return 'Mercury';
    case 2:
      return 'Venus';
    case 3:
      return 'Earth';
    case 4:
      return 'Mars';
    case 5:
      return 'Jupiter';
    case 6:
      return 'Saturn';
    case 7:
      return 'Uranus';
    case 8:
      return 'Neptune';
  }
}
