### ISSUE TITLE
Solve 'Grasshopper - Terminal Game Turn Function'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#29]
https://www.codewars.com/kata/grasshopper-terminal-game-turn-function/train/javascript

**Comment by odv** [comment]
@LaievskyiSasha What's the progress on this exercise?

**Comment by Deobp** [comment]
function doTurn () {
 rollDice();
 move();
 combat();
 getCoins();
 buyHealth();
 printStatus();

}
