### ISSUE TITLE
Solve 'You Can't Code Under Pressure #1'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#3]
https://www.codewars.com/kata/you-cant-code-under-pressure-number-1/train/javascript

**Comment by Deobp** [comment]
function doubleInteger(i) {
  i = i * 2;
  return i;
}

**Comment by odv** [comment]
@LaievskyiSasha Your solution is correct but we can solve this even easier. Read the 'Operators' section in the book and see if you can come up with a better solution.

**Comment by Deobp** [comment]
function doubleInteger(i) { 
  return i*2;
}
