### ISSUE TITLE
Plural

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#314]
https://www.codewars.com/kata/plural/train/javascript

this solution is ok?

```
function plural(n) {
  if (n == 1) return false;
  return true;
}
```

**Comment by odv** [comment]
@LaievskyiSasha  Yes but try to come up with a shorter solution. Think about what condition you have in your `if` statement and see if you can use that condition to reduce the solution to a single line.

**Comment by Deobp** [comment]
```
function plural(n) {
  return n != 1;
}
```
