### ISSUE TITLE
Training JS #6: Basic data types--Boolean and conditional statements if..else

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#315]
https://www.codewars.com/kata/training-js-number-6-basic-data-types-boolean-and-conditional-statements-if-dot-else/train/javascript
dont understand issue
```
function trueOrFalse(val){
  if (Boolean(val) === false)    return 'false';             
  else     return 'true';
}
```

**Comment by odv** [comment]
@LaievskyiSasha  You solved this exercise. Still got issues with understanding what it's asking you?

**Comment by Deobp** [comment]
yes
