### ISSUE TITLE
Solve 'Template Strings'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#32]
https://www.codewars.com/kata/template-strings/train/javascript

**Comment by Deobp** [comment]
let TempleStrings = function(obj, feature) {
  return obj + " are " + feature;
}

**Comment by odv** [comment]
@LaievskyiSasha  Use template strings.

**Comment by Deobp** [comment]
let TempleStrings = function(obj, feature) {
return `${obj + " are " + feature}`;
}

**Comment by odv** [comment]
@LaievskyiSasha  I don't see any template string here. Look at the code again.

**Comment by Deobp** [comment]
```
let TempleStrings = function(obj, feature) {
return `${obj} are ${feature}`;
}
```
