### ISSUE TITLE
No zeros for heros

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#321]
https://www.codewars.com/kata/no-zeros-for-heros/train/javascript

```
function noBoringZeros(n) {
  let str = n.toString().split('');
  for (let i = 0; i < str.length; i++){
    if(str[str.length] == '0'){
    str.pop();
  }else{
    return +str.join('')
    }
}
}
```

**Comment by Deobp** [comment]
```
function noBoringZeros(n) {

  while ( n % 10 == 0 && n != 0 ){
    n = n / 10;
    }

  return n;
}
```

**Comment by odv** [comment]
> https://www.codewars.com/kata/no-zeros-for-heros/train/javascript
> 
> ```
> function noBoringZeros(n) {
>   let str = n.toString().split('');
>   for (let i = 0; i < str.length; i++){
>     if(str[str.length] == '0'){
>     str.pop();
>   }else{
>     return +str.join('')
>     }
> }
> }
> ```

Regarding this solution, check your `for` condition carefully and check if you do need an `else` or not. Besides that, your `if` condition is also not correct.

**Comment by Deobp** [comment]
```
function noBoringZeros(n) {
    let str = n.toString().split('');
    for (let i = str.length; i > 0; i--){
      if (n == 0){
        return 0;
      } else if(str[str.length-1] == '0'){
        str.pop();
      }else{
        return +str.join('')
      }
    }
  }
```

**Comment by Deobp** [comment]
don't understand why my for loop condition incorrect:
```
 for (let i = 0; i < str.length; i++){}
```
it's same logic, but inverted and it works :
```
for (let i = str.length; i > 0; i--){
```
can you help me please to understand differnce?
