### ISSUE TITLE
Draw stairs

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#330]
https://www.codewars.com/kata/draw-stairs/train/javascript
solution is correct, but seems I have mistake or codewars read my '\n' as just string and not like a paragraph

```
function drawStairs(n) {
  if (n > 1){ 
    let str = ''
    for (let i = 1; i <n; i++){
      str += (`I\n${'\xa0'.repeat(i)}`)
    }
    return str + 'I';
  } else {
    return 'I';
  }
}
```

**Comment by odv** [comment]
@LaievskyiSasha You are very close to the correct solution.
First of all, there is no need for `\xa0`. That is actually non-breaking space.

Your issue here is how you compose the string.

Look very careful at the line below the start of your for loop.

**Comment by Deobp** [comment]
Sorry, that was not my finished try, and I post wrong soluetion. Here is updated. Still stuck
```
function drawStairs(n) {
  if (n > 1){ 
    let str = ''
    for (let i = 1; i <n; i++){
      str +=`I\n${'\xa0'.repeat(i)}`
    }
    return str + 'I';
  } else {
    return 'I';
  }
}
```

**Comment by Deobp** [comment]
why with \xa0 test not passed? different spaces or what? or it's about tests?
```
function drawStairs(n) {
  if (n > 1){ 
    let str = ''
    for (let i = 1; i <n; i++){
      str +=`I\n${' '.repeat(i)}`
    }
    return str + 'I';
  } else {
    return 'I';
  }
}
```
