### ISSUE TITLE
They say that only the name is long enough to attract attention. They also said that only a simple Kata will have someone to solve it. This is a sadly story #1: Are they opposite?

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#334]
https://www.codewars.com/kata/they-say-that-only-the-name-is-long-enough-to-attract-attention-they-also-said-that-only-a-simple-kata-will-have-someone-to-solve-it-this-is-a-sadly-story-number-1-are-they-opposite/train/javascript
```
function isOpposite(s1,s2){
  if(s1 === s2) return false;
  return true;
  
}
```

**Comment by odv** [comment]
@LaievskyiSasha  Read the instructions again.

**Comment by Deobp** [comment]
```
function isOpposite(s1,s2){
  let count = 0;
  for(let i = 0; i < s1.length; i++){
    s1[i] === s2[i] ? count += 1 : count -= 1;
  }
  return count + s1.length == 0; 
}

```

**Comment by Deobp** [comment]
```
function isOpposite(s1,s2){
  let str = '';
  if(s1.length != s2.length || s1.length == 0 || s2.length == 0) return false;
  for(let i = 0; i < s1.length; i++){
    s1[i] === s1[i].toUpperCase() ? str += s1[i].toLowerCase() : str += s1[i].toUpperCase(); 
  }
  return str === s2;
}
```

**Comment by liildev** [comment]
function isOpposite(s1, s2) {
    if (string1.length !== string2.length || string1 == "" || string2 == "") {
        return false;
    }
    for (let i = 0; i < string1.length; i++) {
        if (string1[i] === string2[i]) {
            return false;
        }
    }
    return true;
}
