### ISSUE TITLE
Exclamation marks series #11: Replace all vowel to exclamation mark in the sentence

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#336]
https://www.codewars.com/kata/exclamation-marks-series-number-11-replace-all-vowel-to-exclamation-mark-in-the-sentence/train/javascript
```
function replace(s){
  let str ='';
  let vowel = 'aeiouAEIOU';
  for(let i = 0; i < s.length; i++){
    if(vowel.includes(s[i])){
      str += '!';
    }else{
      str += s[i];
    }
  }
  return str;
}
```

**Comment by odv** [comment]
`let vowel = 'aeiouAEIOU';`
You can convert your input to lowercase and not check for caps.
