### ISSUE TITLE
Pre-FizzBuzz Workout #1

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#360]
https://www.codewars.com/kata/pre-fizzbuzz-workout-number-1/train/javascript

**Comment by Deobp** [comment]
```
function preFizz(n) {
  let output = new Array();
  let num = 1;
  while(output.length  < n){
    output.push(num);
    num += 1;
  }
  return output;
}
```

**Comment by DaviJust** [comment]
Thanks for helping. Can i just confirm what is happening, please?
So, you created a function with 2 variables, variable "num", after that you create a loop that use .length, and this makes the number reapeat itself.
So... I found a better explanation here: https://stackoverflow.com/questions/74406248/while-and-array-using-a-loop-with-array/74406483#74406483
