### ISSUE TITLE
Borrower Speak

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#367]
https://www.codewars.com/kata/borrower-speak/train/javascript
I use multiple time .split() and . join(). There is any wat to solve easer?
```
function borrow(s){
  return s.split('!').join('').split('?').join('').split(';').join('').split(':').join('').split('.').join('').split(',').join('').split(' ').join('').toLowerCase();
}
```

**Comment by odv** [comment]
@LaievskyiSasha Yes, with regular expressions. You can read more about a useful regex method here: https://devdocs.io/javascript/global_objects/string/replace
