### ISSUE TITLE
Lottery machine

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#373]
https://www.codewars.com/kata/lottery-machine/train/javascript
I can solve this by using .includes and loop with each number, but is it worth it?

**Comment by odv** [comment]
@LaievskyiSasha Yes, every bit of practice is worth it. After we'll learn regex you'll be able to go back through the exercises and solve them again using them.

**Comment by Deobp** [comment]
```
function lottery(str){
 let uniqInt = []
 str.split('').map(item =>
 if (item == Number(item)){
   if (uniqInt.includes(item){
   1+1;
  }else{
    uniqInt.push(item);
  }
  }
 return uniqInt.length > 0 ?uniqInt.join('') : "One more run!";
   
 
}
```

**Comment by Deobp** [comment]
```
function lottery(str){
 let uniqInt = []
 str.split('').map(item => item == Number(item) ? uniqInt.push(item) : 0 )
 return uniqInt.length > 0 ?uniqInt.join('') : "One more run!";
   
 
}
```

**Comment by Deobp** [comment]
```
function lottery(str){
 let uniqInt = []
 let filterUniq = [];
 str.split('').map(item => item == Number(item) ? uniqInt.push(item) : 0 )
 for(let i = 0; i < uniqInt.length; i++){
   filterUniq.includes(uniqInt[i]) ? 1 : filterUniq.push(uniqInt[i])
 }
  return uniqInt.length > 0 ? filterUniq.join('') : "One more run!";
}
```

**Comment by Deobp** [comment]
How to omit loops and is it possible to use only array.map? I have Array of strings with numbers: ['7022'], is it possible to filter array and return only unique numbers? For example with Set?

**Comment by Deobp** [comment]
solve this with just array.map() and .filter()

**Comment by Deobp** [comment]
```
function lottery(str){
   let set = new Set(str.split('').map(item => Number(item)).filter(item => item > -1));
   if(set.length < 1){
   return "One more run!"
   }
   return set;

}
```

**Comment by Deobp** [comment]
what difference between:
1. ```let set = new Set(str.split('').map(item => Number(item)).filter(item => item > -1));```
2. ```let set = new Set();
    set.add(str.split('').map(item => Number(item)).filter(item => item > -1)```
