### ISSUE TITLE
Shortest Word

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#374]
https://www.codewars.com/kata/shortest-word/train/javascript
Can we omit variable 'minLength', any 1-line solution?
```
function findShort(s){
  let minLength = s.split(' ')[0].length;
  s.split(' ').map((current => current.length < minLength ? minLength = current.length : 0));
  return minLength;
}
```

**Comment by odv** [comment]
@LaievskyiSasha  Omitting really depends on how you are constructing a solution. 
If you choose to go and solve it in one line then yes, you can omit it.

**Comment by Deobp** [comment]
```
function findShort(s){
  return Math.min(...s.split(' ').map(item => item.length));
}

```
