### ISSUE TITLE
Convert boolean values to strings 'Yes' or 'No'.

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#39]
https://www.codewars.com/kata/convert-boolean-values-to-strings-yes-or-no/train/javascript

**Comment by Deobp** [comment]
function boolToWord( bool ){
 return bool ? 'Yes' : 'No';
}

**Comment by Deobp** [comment]
this variat is good? or better to use if, else?

**Comment by odv** [comment]
@LaievskyiSasha  Ternary is great.
