### ISSUE TITLE
Sum Arrays

### ISSUE THREAD

**Issue by Deobp** [js-mentorship-sasha/javascript#390]
https://www.codewars.com/kata/53dc54212259ed3d4f00071c/train/javascript
Don't know how to solve it with recursion

**Comment by odv** [comment]
@LaievskyiSasha  We will solve this one with recursion together. Please think about the base case. How will you terminate the recursion? How do you build the stack?

**Comment by Deobp** [comment]
```
function sum (numbers) {
  if(numbers.length == 0) return 0;
  return numbers.pop() + sum(numbers);
}
```

**Comment by Deobp** [comment]
```
function sum (numbers, def = numbers.length) {
  if(def == 0) return 0;
  return numbers[def -1] + sum(numbers, def -= 1);
}

```
