### ISSUE TITLE
Write a function that accepts a string ip address and returns country, city and ISP(use ipify API)

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#395]
Use ipfy API: https://geo.ipify.org/signup
Documentation: https://geo.ipify.org/docs

[Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch): https://geo.ipify.org/api/v1?apiKey=YOUR_API_KEY&ipAddress=8.8.8.8 

**YOUR_API_KEY** is your actual API key that you received when signing up

**ipAddress** will be the actual ip address you receive as input.

**DO NOT PASTE API KEY IN COMMENTS. ALWAYS KEEP IT PRIVATE!**

Example output: "Country: US,  city: Mountain View, ISP: Google LLC"

**Comment by Deobp** [comment]
```
function info(){
    fetch('https://geo.ipify.org/api/v1?apiKey=KEY&ipAddress=8.8.8.8')
        .then((response) => {
            return response.json();
    })
        .then((myJson) => {
            console.log(`Contry: ${myJson.location.country}, City: ${myJson.location.city}, ISP: ${myJson.as.name}`);
    });
}
```

**Comment by Deobp** [comment]
```
function inf(ip){
    fetch(`https://geo.ipify.org/api/v1?apiKey=KEY&ipAddress=${ip}`)
        .then((response) => {
            return response.json();
    })
        .then((myJson) => {
            console.log(`Contry: ${myJson.location.country}, City: ${myJson.location.city}, ISP: ${myJson.as.name}`);
    });
}
```
