### ISSUE TITLE
Solve 'Grasshopper - Messi goals function'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#4]
https://www.codewars.com/kata/grasshopper-messi-goals-function/train/javascript

**Comment by Deobp** [comment]
function goals (laLigaGoals, copaDelReyGoals, championsLeagueGoals) {
  let l = laLigaGoals;
  let c = copaDelReyGoals;
  let x = championsLeagueGoals;
  let sum = l + c + x;
  return sum;
}

**Comment by odv** [comment]
@LaievskyiSasha First of all, you don't need these variables(l,c,x). You already have the parameters. Just return the sum of them.

**Comment by Deobp** [comment]
function goals (laLigaGoals, copaDelReyGoals, championsLeagueGoals) {
let sum = laLigaGoals + copaDelReyGoals + championsLeagueGoals;
return sum;
}

**Comment by Deobp** [comment]
@odv 
function goals (laLigaGoals, copaDelReyGoals, championsLeagueGoals) {
return laLigaGoals + copaDelReyGoals + championsLeagueGoals;
}
