### ISSUE TITLE
Calculate the percentage of the hours spent on each activity and append the percentage to the inner array

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#408]
let log = [['Codewars issues', 5], ['Create notes', 15], ['gym', 1], ['eat', 1]]

**Comment by odv** [comment]
After you've done the task above, remove percentages from the JavaScript multidimensional array.

**Comment by odv** [comment]
After you've done the task above,  iterate through the multidimensional array.

**Comment by Deobp** [comment]
for (let i = 0; i < log.length; i++){
    log[i].push(Number((log[i][1] / 24 * 100).toFixed(2)))
}

for (let i = 0; i < log.length; i++){
    console.log(...log)
}

**Comment by Deobp** [comment]
> 
> 
> After you've done the task above, remove percentages from the JavaScript multidimensional array.

```
for (let i = 0; i < log.length; i++){
    log[i].pop()
}
```

**Comment by Deobp** [comment]
```
for (let i = 0; i < log.length; i++){
    console.log(log[i])
}
```
