### ISSUE TITLE
Loop and format output according to this

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#410]
let log = [['Codewars issues', 5], ['Create notes', 15], ['gym', 1], ['eat', 1]]

Output: 
[0,0] = Codewars issues
[0,1] = 5
[1,0] = Create notes
[1,1] = 15
[2,0] = gym
[2,1] = 1
[3,0] = eat
[3,1] = 1

**Comment by Deobp** [comment]
```
for(let i = 0; i < log.length; i++){
    for(let iter = 0; iter < log[i].length; iter ++){
        console.log(`[${i},${iter}] = ${log[i][iter]}`)
    }
}
```
