### ISSUE TITLE
Build a JavaScript tip calculator

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#411]
The tip calculator should have the following components: 

+ Bill amount
+ Tip percentage: 
    + 30% outstanding
    + 20% good
    + 15% it was ok
    + 10% bad
    + 5% terrible
+ How many people share the bill

Use an object and properties/methods to solve this.

Return: amount each person needs to pay.

**Comment by Deobp** [comment]
What input do we have? Number of people, bill and tip? How tip respresents?

**Comment by Deobp** [comment]
```

    let obj ={
        pay : function(bill, percentage, people){
            return percentage > 30 ? (bill * 0.3 + bill) / people : (bill * (percentage / 100) + bill) / people;
        },
    }
```
