### ISSUE TITLE
function callback exercise

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#432]
Create a function called **introduction** that accepts a name argument, a family argument and a callback function so that when called it will produce the following output:

introduction('A,'C', greeting);

output:  // Hello A C, welcome to JavaScript!

**Comment by Deobp** [comment]
```
function greeting(a,b){
    return `Hello ${a} ${b}, welcome to JavaScript!`
}


function introduction(name,family,anotherFunction){
    return anotherFunction(name,family)
    }
console.log(introduction('a','c',greeting))``
```
