### ISSUE TITLE
Solve 'Fix the Bugs (Syntax) - My First Kata'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#45]
https://www.codewars.com/kata/fix-the-bugs-syntax-my-first-kata/train/javascript

**Comment by Deobp** [comment]
function myFirstKata(a,b) {
  if (typeof(a) === 'number' && typeof(b) === 'number') {
  return  (a % b) + (b % a);
  } else {
    return false;
}
}
