### ISSUE TITLE
Solve 'Can we divide it?'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#47]
https://www.codewars.com/kata/can-we-divide-it/train/javascript

**Comment by Deobp** [comment]
```
function isDivideBy(number, a, b) {
 if (number % a === 0 && number % b === 0) {
 return true;
} else {
 return false;
 }
 } 

```

**Comment by frommenine** [comment]
Why did you write "a === 0" and "b === 0"? What is it for?

**Comment by Deobp** [comment]
> 
```number % a === 0' and 'number % b ===0```
The result of number % a is the remainder of the integer division of number by b. After I check if this remainder is equal to 0 or not to understand if it is integer.
Triple equal it means strict comparison.
