### ISSUE TITLE
Solve 'Volume of a Cuboid'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#53]
https://www.codewars.com/kata/volume-of-a-cuboid/train/javascript

Functions can have functions inside it, it's a perfect valid syntax. You just need to return the volume.

**Comment by Deobp** [comment]
```
let Kata = (function() {
  function Kata() {}

  Kata.getVolumeOfCuboid = function(length, width, height) {
    return length * width * height;
  };

  return Kata;

})();
```

**Comment by Deobp** [comment]
don't understood functiont logic
