### ISSUE TITLE
Solve 'Keep Hydrated!'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#54]
https://www.codewars.com/kata/keep-hydrated-1/train/javascript

You need to use the https://devdocs.io/javascript/global_objects/math object. Read through the documentation and find the method that you need. In case I haven't specified you, a method is a function that is contained in an object and it's accessed like obj.method() while a function is accessed like **functionName()**.

**Comment by Deobp** [comment]
```
function litres(time) {
  return Math.trunc(time * 0.5);
}
```
