### ISSUE TITLE
Solve FizzBuzz

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#55]
This is not a codewars problem.

Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”.

**Comment by Deobp** [comment]
function Fbz(){
for (let number = 1; number < 101; number++) {
if (number%3 == 0 && number%5 == 0) {
alert "FizzBuzz";
 } else if (number%3 == 0) {
 alert "Fizz";
 } else if (number%5 == 0) {
 alert "Buzz";
 } else {
 alert number;
 }
}

**Comment by odv** [comment]
@LaievskyiSasha Output should be this:

```
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz
```

Use console.log() to output the values.

**Comment by Deobp** [comment]
```
function fizzBuzz(){
for (let number = 1; number < 101; number++) {
if (number % 3 == 0 && number % 5 == 0) {
console.log("FizzBuzz");
} else if (number % 3  == 0) {
console.log ("Fizz");
} else if (number % 5 == 0) {
console.log("Buzz");
} else {
console.log(number);
}
}
}
```
