### ISSUE TITLE
Solve 'Returning Strings'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#6]
https://www.codewars.com/kata/returning-strings/train/javascript

**Comment by Deobp** [comment]
function greet(name){

  let greatings = ("Hello, " + name + " how are you doing today?");

  return greatings;
}

**Comment by odv** [comment]
@LaievskyiSasha You don't need round paranthesis in the greetings variable. Your solution works though, great job. Try and see if you can solve it using template strings.

**Comment by Deobp** [comment]
function greet(name){
return "Hello, " + name + " how are you doing today?";;
}
