### ISSUE TITLE
Solve 'Dollars and Cents'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#67]
https://www.codewars.com/kata/dollars-and-cents/train/javascript

@LaievskyiSasha  Read about the toFixed method

**Comment by Deobp** [comment]
```
function formatMoney(amount){
  return '$' + amount.toFixed(2);
}
```

**Comment by Deobp** [comment]
next time dont give me tips please ;]

**Comment by odv** [comment]
@LaievskyiSasha Try and also solve this exercise using template strings.

**Comment by Deobp** [comment]
```
function formatMoney(amount){
  return `$${amount.toFixed(2)}`;
}
```
