### ISSUE TITLE
Solve 'simple calculator'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#7]
https://www.codewars.com/kata/simple-calculator

**Comment by Deobp** [comment]
function calculator(a,b,sign){
//mistake a !=
if a != Number {
  return ("unknown value", 'calculate');
  } else { 
  return ("", 'calculate');
  }
   
  
if b != Number {
  return ("unknown value", 'calculate');
  } else {
  return ("", 'calculate');
  // mistake
if sign != ("* + - /") {
  return ("", 'calculate');
  } else {
  return ("", 'unknown value');
}

  //here where I stop

**Comment by odv** [comment]
@LaievskyiSasha I am going to give you a hint: you need a "switch" statement.

**Comment by Deobp** [comment]
function calculator(a,b,sign){
switch (sign) {
  case '+': 
  return a + b;
 case '-':
 return a - b;
  break;
  case '*':
  return a * b;
  break;
  case '/':
  return a / b;
  break;
  default: 
  return ("unknown value");
  }
}

**Comment by Deobp** [comment]
function calculator(a,b,sign){
switch (sign) {
if a,b=numbers; {                                   // can't find how to type in properly
case '+':
return a + b;
case '-':
return a - b;
break;
case '*':
return a * b;
break;
case '/':
return a / b;
break;
default:
return ("unknown value");
 } else {
 return ("unknown value")
}
}
}

**Comment by odv** [comment]
@LaievskyiSasha  What's your progress on this exercise?

**Comment by Deobp** [comment]
function calculator(a,b,sign){

if (typeof a === 'number' && typeof b === 'number') {

  switch (sign) {
    case '+':
      return a + b;
    case '-':
      return a - b;
    case '*':
      return a * b;
    case '/':
      return a / b;
    default:
      return ("unknown value");
  }
} else {
return ("unknown value");
  }
}
