### ISSUE TITLE
Solve 'If you can't sleep, just count sheep!!'

### ISSUE THREAD

**Issue by odv** [js-mentorship-sasha/javascript#8]
https://www.codewars.com/kata/if-you-cant-sleep-just-count-sheep/train/javascript

**Comment by Deobp** [comment]
1st try, not finished
let countSheep = function (num){
    let s = " sheep..."
    let n = "";
    let i = 0
 while ( i < num){
i++;
i += s;
 }
return i;
}

**Comment by Deobp** [comment]
So, I need return num+" sheep..." + (num times) num+num+" sheep..." ... 
Or return num times   " sheep..." and add here counting from 1 to num.
We need use loop.
create string:
 let s =" sheep..."; 
create loop:
for (let  i= 1; i < num; i++) {
if (i < num) {
return i + s;
}
}
Looks like I need loop coun with adding string and then return?

**Comment by Deobp** [comment]
let countSheep = function (num){
    let q ="";
    
 for (let i=1; i <= num;i++) {
  q=q+i + " " + "sheep" +"...";

 }
return q;
}

**Comment by odv** [comment]
@LaievskyiSasha  How would you simplify this line of code?

```(javascript)
q=q+i + " " + "sheep" +"...";
```

**Comment by Deobp** [comment]
let countSheep = function (num){
let q ="";

for (let i=1; i <= num;i++) {
q=q+i + " sheep...";

}
return q;
}
